Repository wavesplatform/Waves, pull requests merged in 2019-07, with the labels that each got.

#2433 Add gRPC extension DEB package to packageAll task
  build.sbt
Labels: enhancement

#2383 NODE-1809: /debug/stateChanges and ApiErrors fixes
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/BlocksApiGrpcImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/GRPCErrors.scala
  node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/ScriptLogSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/AtomicSwapSmartContractSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/SignAndBroadcastApiSuite.scala
  node/src/main/scala/com/wavesplatform/api/common/CommonBlocksApi.scala
  node/src/main/scala/com/wavesplatform/api/http/AddressApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/ApiError.scala
  node/src/main/scala/com/wavesplatform/api/http/ApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/BlocksApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/CommonApiFunctions.scala
  node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/UtilsApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/alias/AliasApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/apiErrors.scala
  node/src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/package.scala
  node/src/main/scala/com/wavesplatform/consensus/nxt/api/http/NxtConsensusApiRoute.scala
  node/src/main/scala/com/wavesplatform/http/ApiMarshallers.scala
  node/src/main/scala/com/wavesplatform/http/DebugApiRoute.scala
  node/src/main/scala/com/wavesplatform/http/WavesApiRoute.scala
  node/src/test/scala/com/wavesplatform/api/http/TraceResultJsonTest.scala
  node/src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/AliasBroadcastRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/AssetsBroadcastRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/ConsensusRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/DebugApiRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/LeaseBroadcastRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/PaymentRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/PeersRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/UtilsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/WalletRouteSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/OracleDataTest.scala
Labels: breaking, refactoring

#2413 NODE-333: Allow to override directory via waves.conf in DEB installation
  node/build.sbt
  node/src/main/resources/deprecated-settings.conf
  node/src/main/scala/com/wavesplatform/db/package.scala
  node/src/main/scala/com/wavesplatform/settings/package.scala
Labels: enhancement

#2412 Show importer time when interrupted
  node/src/main/scala/com/wavesplatform/Importer.scala
Labels: enhancement

#2442 NODE-1834: Restart service in postinst
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/utils/Schedulers.scala
  node/src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala
  node/src/package/debian/postinst
Labels: wip

#2453 SC-409 Names of extracted funcs
  lang/js/src/main/scala/JsAPI.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/DecompilerTest.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/utils/Serialize.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/FunctionHeader.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Decompiler.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/EvaluatorV1.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/NativeFunction.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/InvokeScriptTransaction.scala
Labels: hold

#2437 SC-396 Separate docstrings
  build.sbt
  lang/doc-data-v1.json
  lang/doc-data-v2.json
  lang/doc-data-v3.json
  lang/js/src/main/scala/JsAPI.scala
  lang/jvm/src/main/scala/com/wavesplatform/utils/DocExport.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/Common.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/ExpressionCompilerV1Test.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/package.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/v1/ScriptEstimatorTest.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/v1/evaluator/SplitFunctionTest.scala
  lang/jvm/src/test/scala/com/wavesplatform/utils/DocExportTest.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/CTX.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerContext.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/ContractCompiler.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/ExpressionCompiler.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Types.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/EvaluatorV1.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/NativeFunction.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/CryptoContext.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
  node/src/test/scala/com/wavesplatform/utils/UtilsSpecification.scala
  project/Dependencies.scala
  project/DocSourceData.scala
  project/Tasks.scala
  project/plugins.sbt
Labels: hold

#2443 SC-365 V3 doc categories
  lang/doc-data-v3.json
  lang/doc/v1/data.json
  lang/doc/v2/data.json
  lang/doc/v3/funcs/account-data-storage-functions.hjson
  lang/doc/v3/funcs/blockchain-functions.hjson
  lang/doc/v3/funcs/byte-array-functions.hjson
  lang/doc/v3/funcs/converting-functions.hjson
  lang/doc/v3/funcs/encoding-and-decoding-functions.hjson
  lang/doc/v3/funcs/exception-functions.hjson
  lang/doc/v3/funcs/extracting-data-functions.hjson
  lang/doc/v3/funcs/internal-functions.hjson
  lang/doc/v3/funcs/list-functions.hjson
  lang/doc/v3/funcs/math-functions.hjson
  lang/doc/v3/funcs/operators.hjson
  lang/doc/v3/funcs/optional-value-functions.hjson
  lang/doc/v3/funcs/string-functions.hjson
  lang/doc/v3/funcs/verification-functions.hjson
  lang/doc/v3/vars.json
  lang/func-doc.template.md
  lang/jvm/src/main/scala/com/wavesplatform/utils/DocExport.scala
  lang/jvm/src/main/scala/com/wavesplatform/utils/doc/DocExport.scala
  lang/jvm/src/main/scala/com/wavesplatform/utils/doc/DocExportV3.scala
  lang/jvm/src/main/scala/com/wavesplatform/utils/doc/MustacheDoc.scala
  lang/jvm/src/main/scala/com/wavesplatform/utils/doc/RideFullContext.scala
  lang/jvm/src/test/scala/com/wavesplatform/utils/DocExportTest.scala
  project/Tasks.scala
  project/plugins.sbt
Labels: hold

#2411 SC-382 Callable func signatures
  .gitignore
  build.sbt
  lang/js/src/main/scala/JsAPI.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/ContractSerdeTest.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/ContractCompilerTest.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/DecompilerTest.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/MetaTest.scala
  lang/shared/src/main/protobuf/DAppMeta.proto
  lang/shared/src/main/scala/com/wavesplatform/lang/contract/ContractSerDe.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/contract/DApp.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/contract/meta/MetaMapper.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/contract/meta/MetaMapperStrategy.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/contract/meta/MetaMapperStrategyV1.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/contract/meta/MetaVersion.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/contract/meta/RecKeyValue.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/script/ContractScript.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/script/ScriptReader.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/BaseGlobal.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/ContractCompiler.scala
  lang/shared/src/test/scala/com/wavesplatform/lang/v1/testing/TypedScriptGen.scala
  node/src/main/scala/com/wavesplatform/api/http/UtilsApiRoute.scala
  node/src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/UtilsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SetScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/transaction/SetAssetScriptTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/smart/script/ContractScriptComplexityTest.scala
  project/Dependencies.scala
Labels: hold

#2451 SC-406 Stateful REPL
  lang/js/src/main/scala/JsAPI.scala
  lang/jvm/src/test/scala/com/wavesplatform/lang/v1/ReplTest.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/Repl.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Terms.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/SetAssetScriptTransactionSuite.scala
  node/src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/TransactionValidationErrorPrintTest.scala
Labels: hold
