Repository wavesplatform/Waves, pull requests merged in 2019-12, with the labels that each got.

#2797 SC-506: test for payment overdraft in InvokeScript tx
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/RideV4ActivationSuite.scala
  node/src/main/scala/com/wavesplatform/transaction/Asset.scala
  node/src/test/scala/com/wavesplatform/http/AssetsBroadcastRouteSpec.scala
Labels: wip

#2819 NODE-1934: Multiple tx status request
  lang/shared/src/main/scala/com/wavesplatform/common/state/ByteStr.scala
  node/src/main/protobuf/waves/api.proto
  node/src/main/scala/com/wavesplatform/api/http/AutoParamsDirective.scala
  node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
  node/src/main/scala/com/wavesplatform/network/HandshakeHandler.scala
  node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
Labels: feature

#2824 NODE-1947: Reject txs from UTX when blockchain is stale
  node-it/src/test/resources/template.conf
  node-it/src/test/scala/com/wavesplatform/it/sync/UtxSuite.scala
  node/src/main/resources/application.conf
  node/src/main/scala/com/wavesplatform/settings/UtxSettings.scala
  node/src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala
  node/src/test/scala/com/wavesplatform/mining/MiningWithRewardSuite.scala
  node/src/test/scala/com/wavesplatform/settings/UTXSettingsSpecification.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
Labels: enhancement

#2826 Fix MinerStateTestSuite
  node-it/src/test/scala/com/wavesplatform/it/sync/MinerStateTestSuite.scala
Labels: bug

#2850 NODE-1934: Fix tx status swagger
  node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
Labels: bug

#2838 PB microblocks fixes
  node/src/main/resources/logback.xml
  node/src/main/scala/com/wavesplatform/network/BasicMessagesRepo.scala
  node/src/main/scala/com/wavesplatform/network/HistoryReplier.scala
  node/src/main/scala/com/wavesplatform/network/LegacyFrameCodec.scala
  node/src/main/scala/com/wavesplatform/network/MessageCodec.scala
  node/src/main/scala/com/wavesplatform/network/MessageObserver.scala
  node/src/main/scala/com/wavesplatform/network/messages.scala
Labels: bug

#2853 PB scripts and FC fixes
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/test/scala/com/wavesplatform/transaction/InvokeScriptTransactionSpecification.scala
Labels: bug
