Repository wavesplatform/Waves, pull requests merged in 2019-11, with the labels that each got.

#2707 NODE-1928: LeaseTransaction new format
  blockchain-updates/src/main/scala/com/wavesplatform/events/BlockchainUpdates.scala
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-generator/src/main/scala/com/wavesplatform/generator/Preconditions.scala
  node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/ObsoleteHandlersSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/BigStringSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/LeaseSmartContractsTestSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/LeaseStatusTestSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/LeasingTransactionsSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/api/common/CommonAccountApi.scala
  node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/leasing/LeaseApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/package.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/LeaseRequest.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/SignedLeaseV1Request.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionParsers.scala
  node/src/main/scala/com/wavesplatform/transaction/lease/LeaseTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/lease/LeaseTransactionV1.scala
  node/src/main/scala/com/wavesplatform/transaction/lease/LeaseTransactionV2.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/LeaseTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/LeaseTxValidator.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/Validations.scala
  node/src/test/scala/com/wavesplatform/BlocksTransactionsHelpers.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/LeaseV1Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/LeaseV2Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/SignedLeaseV1Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/SignedLeaseV2Request.scala
  node/src/test/scala/com/wavesplatform/http/LeaseBroadcastRouteSpec.scala
  node/src/test/scala/com/wavesplatform/state/RollbackSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ScriptsCountTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SponsorshipDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/patch/CancelLeaseOverflowTest.scala
  node/src/test/scala/com/wavesplatform/state/reader/StateReaderEffectiveBalancePropertyTest.scala
  node/src/test/scala/com/wavesplatform/transaction/LeaseTransactionSpecification.scala
Labels: enhancement

#2712 NODE-1928: LeaseV1 serialization fixes
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/BaseTxJson.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/CreateAliasTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/LeaseTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/TransferTxSerializer.scala
Labels: bug

#2717 NODE-1928: Exchange transaction V4
  benchmark/src/test/scala/com/wavesplatform/serialization/protobuf/SmartNoSmartBenchmark.scala
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-generator/src/main/scala/com/wavesplatform/generator/SmartGenerator.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/ExchangeTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/ExchangeWithContractsSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/package.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/ExchangeTransactionSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/SignAndBroadcastApiSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/TransferNFTSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/package.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/ExchangeRequest.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBOrders.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/serialization/JsonSerializable.scala
  node/src/main/scala/com/wavesplatform/state/Portfolio.scala
  node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
  node/src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/transaction/Proven.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionParsers.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/AssetPair.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/ExchangeTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/ExchangeTransactionV1.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/ExchangeTransactionV2.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/Order.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderJson.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderOps.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderV1.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderV2.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderV3.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/package.scala
  node/src/main/scala/com/wavesplatform/transaction/description/ByteEntities.scala
  node/src/main/scala/com/wavesplatform/transaction/package.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/CreateAliasTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/ExchangeTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/LeaseCancelTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/LeaseTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/OrderSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/TransferTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/package.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/package.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/TxValidator.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/ExchangeTxValidator.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/SignedExchangeRequest.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/SignedExchangeRequestV2.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ScriptsCountTest.scala
  node/src/test/scala/com/wavesplatform/transaction/ExchangeTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/OrderSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/assets/exchange/OrderJsonSpecification.scala
Labels: enhancement

#2726 NODE-1928: Issue V4
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-generator/src/main/scala/com/wavesplatform/generator/Preconditions.scala
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/CustomFeeTransactionSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/NFTBalanceSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/ObsoleteHandlersSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/ExchangeTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/package.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/ExchangeTransactionSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/package.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/IssueRequest.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/IssueV1Request.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/IssueV2Request.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/package.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/serialization/Deser.scala
  node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionParsers.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/IssueTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/IssueTransactionV1.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/IssueTransactionV2.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/SetAssetScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/IssueTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/package.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/SetScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/IssueTxValidator.scala
  node/src/test/scala/com/wavesplatform/BlocksTransactionsHelpers.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/api/http/AssetsApiRouteSpec.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/IssueV1Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/IssueV2Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/SignedIssueV1Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/SignedIssueV2Request.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterBurnTest.scala
  node/src/test/scala/com/wavesplatform/network/MessageCodecSpec.scala
  node/src/test/scala/com/wavesplatform/state/RollbackSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/CommonValidationTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/MassTransferTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ScriptsCountTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SponsorshipDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/TransactionValidationErrorPrintTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/TransferTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/CallableV4DiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/MultiPaymentInvokeDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/SmartAssetEvalTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/NotaryControlledTransferScenarioTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/ScriptedSponsorTest.scala
  node/src/test/scala/com/wavesplatform/transaction/ExchangeTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/IssueTransactionV1Specification.scala
  node/src/test/scala/com/wavesplatform/transaction/IssueTransactionV2Specification.scala
  node/src/test/scala/com/wavesplatform/transaction/ReissueTransactionV2Specification.scala
  node/src/test/scala/com/wavesplatform/transaction/SponsorFeeTransactionSpecification.scala
Labels: enhancement

#2731 NODE-1928: Reissue V4
  benchmark/src/test/scala/com/wavesplatform/transaction/smart/VerifierLoggerBenchmark.scala
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/ObsoleteHandlersSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/ReissueTransactionV1Suite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/package.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/ReissueRequest.scala
  node/src/main/scala/com/wavesplatform/mining/Miner.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/serialization/package.scala
  node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
  node/src/main/scala/com/wavesplatform/state/diffs/DiffsCommon.scala
  node/src/main/scala/com/wavesplatform/state/diffs/FeeValidation.scala
  node/src/main/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/transaction/Transaction.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionParsers.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/BurnTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/ReissueTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/ReissueTransactionV1.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/ReissueTransactionV2.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/SetAssetScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/SponsorFeeTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/ExchangeTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/IssueTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/ReissueTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/InvokeScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/Verifier.scala
  node/src/main/scala/com/wavesplatform/transaction/transfer/MassTransferTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/transfer/TransferTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/ReissueTxValidator.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/ReissueV1Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/ReissueV2Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/SignedReissueV1Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/SignedReissueV2Request.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterBurnTest.scala
  node/src/test/scala/com/wavesplatform/state/RollbackSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ScriptsCountTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/transaction/GenericTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/ReissueTransactionV1Specification.scala
  node/src/test/scala/com/wavesplatform/transaction/ReissueTransactionV2Specification.scala
  node/src/test/scala/com/wavesplatform/transaction/SetAssetScriptTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/SetScriptTransactionSpecification.scala
Labels: enhancement

#2734 NODE-1928: Burn V4
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/ObsoleteHandlersSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/NoOrderProofsSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/package.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/BurnRequest.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionParsers.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/BurnTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/BurnTransactionV1.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/BurnTransactionV2.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/BurnTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/TxConstraints.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/BurnTxValidator.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/BurnV1Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/BurnV2Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/SignedBurnV1Request.scala
  node/src/test/scala/com/wavesplatform/api/http/requests/SignedBurnV2Request.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterBurnTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ScriptsCountTest.scala
  node/src/test/scala/com/wavesplatform/transaction/BurnTransactionSpecification.scala
Labels: enhancement

#2736 NODE-1928: Data V4
  benchmark/src/test/scala/com/wavesplatform/transaction/smart/VerifierLoggerBenchmark.scala
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-generator/src/main/scala/com/wavesplatform/generator/OracleTransactionGenerator.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/ScriptLogSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/ExchangeWithContractsSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/InvokeScriptTransactionSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/ExchangeSmartAssetsSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/NoOrderProofsSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/DataTransactionSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/DataRequest.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/state/DataEntry.scala
  node/src/main/scala/com/wavesplatform/transaction/DataTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/description/ByteEntities.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/DataTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/TxConstraints.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/DataTxValidator.scala
  node/src/test/scala/com/wavesplatform/BlocksTransactionsHelpers.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/state/RollbackSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/DataTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ScriptsCountTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/CommonFunctionsTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/SerContextFunctionsTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/NotaryControlledTransferScenarioTest.scala
  node/src/test/scala/com/wavesplatform/transaction/BurnTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/DataTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/ReissueTransactionV1Specification.scala
  node/src/test/scala/com/wavesplatform/transaction/smart/script/estimator/FunctionComplexityTest.scala
Labels: enhancement

#2737 NODE-1928: MassTransfer V4
  benchmark/src/test/scala/com/wavesplatform/serialization/protobuf/ProtoBufBenchmark.scala
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-generator/src/main/scala/com/wavesplatform/generator/utils/Gen.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/MassTransferSmartContractSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/MassTransferTransactionSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/account/AddressOrAlias.scala
  node/src/main/scala/com/wavesplatform/account/Alias.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/SignedMassTransferRequest.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/serialization/Deser.scala
  node/src/main/scala/com/wavesplatform/state/DataEntry.scala
  node/src/main/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/MassTransferTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/description/ByteEntities.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/CreateAliasTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/IssueTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/MassTransferTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/TransferTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/transfer/MassTransferTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/TxConstraints.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/MassTransferTxValidator.scala
  node/src/test/scala/com/wavesplatform/DeserializationTests.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/state/RollbackSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ScriptsCountTest.scala
  node/src/test/scala/com/wavesplatform/transaction/MassTransferTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
Labels: enhancement

#2739 NODE-1928: InvokeScript V4
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/Serde.scala
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/account/AddressOrAlias.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/InvokeScriptRequest.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/serialization/Deser.scala
  node/src/main/scala/com/wavesplatform/serialization/package.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/InvokeScriptTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/TransferTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/InvokeScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/InvokeScriptTxValidator.scala
  node/src/test/scala/com/wavesplatform/BlocksTransactionsHelpers.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/api/http/TraceResultJsonTest.scala
  node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/CallableV4DiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/MultiPaymentInvokeDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/package.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala
  node/src/test/scala/com/wavesplatform/transaction/InvokeScriptTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/MassTransferTransactionSpecification.scala
Labels: enhancement

#2741 NODE-1928: SetScript V4
  benchmark/src/test/scala/com/wavesplatform/state/StateSyntheticBenchmark.scala
  node-generator/src/main/scala/com/wavesplatform/generator/MultisigTransactionGenerator.scala
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-generator/src/main/scala/com/wavesplatform/generator/OracleTransactionGenerator.scala
  node-generator/src/main/scala/com/wavesplatform/generator/Preconditions.scala
  node-generator/src/main/scala/com/wavesplatform/generator/SmartGenerator.scala
  node-it/src/test/scala/com/wavesplatform/it/IntegrationSuiteWithThreeAddresses.scala
  node-it/src/test/scala/com/wavesplatform/it/async/SmartTransactionsConstraintsSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/RollbackSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/ScriptLogSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/AtomicSwapSmartContractSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/BigLetChain.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/BigStringSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/RIDEFuncSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/ScriptExecutionErrorSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/SetScriptTransactionSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/SetAssetScriptTransactionSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/SignedSetScriptRequest.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/SetScriptTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/SetScriptTransaction.scala
  node/src/test/scala/com/wavesplatform/BlocksTransactionsHelpers.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/database/LevelDBWriterSpec.scala
  node/src/test/scala/com/wavesplatform/db/ScriptCacheTest.scala
  node/src/test/scala/com/wavesplatform/state/RollbackSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/CommonValidationTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ScriptsCountTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SetScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/CallableV4DiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/MultiPaymentInvokeDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/ObsoleteTransactionBindingsTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/ScriptedSponsorTest.scala
  node/src/test/scala/com/wavesplatform/transaction/SetScriptTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
Labels: enhancement

#2743 NODE-1928: SponsorFee V4
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/SetAssetScriptTransactionSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/SponsorshipSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/SignedSetAssetScriptRequest.scala
  node/src/main/scala/com/wavesplatform/api/http/requests/SponsorFeeRequest.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/SetAssetScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/SponsorFeeTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/SetAssetScriptTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/SponsorFeeTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/SetAssetScriptTxValidator.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/SponsorFeeTxValidator.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/state/diffs/CommonValidationTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ScriptsCountTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SponsorshipDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/SmartAssetEvalTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/ScriptedSponsorTest.scala
  node/src/test/scala/com/wavesplatform/transaction/SetAssetScriptTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/SponsorFeeTransactionSpecification.scala
Labels: enhancement

#2744 NODE-1928: Remove byte descriptors
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
  node-generator/src/main/scala/com/wavesplatform/generator/config/FicusImplicits.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBWriterAddressTransactions.scala
  node/src/main/scala/com/wavesplatform/serialization/package.scala
  node/src/main/scala/com/wavesplatform/state/extensions/AddressTransactions.scala
  node/src/main/scala/com/wavesplatform/state/extensions/composite/CompositeAddressTransactions.scala
  node/src/main/scala/com/wavesplatform/state/package.scala
  node/src/main/scala/com/wavesplatform/transaction/CreateAliasTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/DataTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/GenesisTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/PaymentTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/Transaction.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionParser.scala
  node/src/main/scala/com/wavesplatform/transaction/TransactionParsers.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/BurnTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/IssueTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/ReissueTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/SetAssetScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/SponsorFeeTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/ExchangeTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/description/ByteEntities.scala
  node/src/main/scala/com/wavesplatform/transaction/lease/LeaseCancelTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/lease/LeaseTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/GenesisTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/PaymentTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/InvokeScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/SetScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/transfer/MassTransferTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/transfer/TransferTransaction.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/state/TransactionsByAddressSpec.scala
  node/src/test/scala/com/wavesplatform/state/utils/package.scala
  node/src/test/scala/com/wavesplatform/transaction/GenericTransactionSpecification.scala
Labels: refactoring

#2748 Protobuf InvokeScript serialization fixes
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/test/scala/com/wavesplatform/transaction/InvokeScriptTransactionSpecification.scala
Labels: bug

#2738 NODE-1972: Transactions merkle root
  grpc-server/build.sbt
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/PBImplicitConversions.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/PoSSuite.scala
  node/build.sbt
  node/src/main/scala/com/wavesplatform/GenesisBlockGenerator.scala
  node/src/main/scala/com/wavesplatform/block/Block.scala
  node/src/main/scala/com/wavesplatform/block/package.scala
  node/src/main/scala/com/wavesplatform/block/serialization/BlockSerializer.scala
  node/src/main/scala/com/wavesplatform/block/validation/Validators.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
  node/src/main/scala/com/wavesplatform/database/package.scala
  node/src/main/scala/com/wavesplatform/mining/Miner.scala
  node/src/main/scala/com/wavesplatform/protobuf/block/PBBlocks.scala
  node/src/main/scala/com/wavesplatform/state/NgState.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/WavesEnvironment.scala
  node/src/test/scala/com/wavesplatform/BlockGen.scala
  node/src/test/scala/com/wavesplatform/BlocksTransactionsHelpers.scala
  node/src/test/scala/com/wavesplatform/block/TransactionsRootSpec.scala
  node/src/test/scala/com/wavesplatform/consensus/FPPoSSelectorTest.scala
  node/src/test/scala/com/wavesplatform/history/package.scala
  node/src/test/scala/com/wavesplatform/lagonaki/mocks/TestBlock.scala
  node/src/test/scala/com/wavesplatform/lagonaki/unit/BlockSpecification.scala
  node/src/test/scala/com/wavesplatform/mining/BlockV5Test.scala
  node/src/test/scala/com/wavesplatform/state/HistoryTest.scala
  node/src/test/scala/com/wavesplatform/state/TransactionsByAddressSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/BlockDifferTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/ParseFunctionsTest.scala
  node/src/test/scala/com/wavesplatform/transaction/BlockchainUpdaterTest.scala
  project/Dependencies.scala
Labels: wip

#2745 NODE-1928: PB transactions
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AccountsApiGrpcImpl.scala
  node/src/main/scala/com/wavesplatform/database/Keys.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
  node/src/main/scala/com/wavesplatform/network/BasicMessagesRepo.scala
  node/src/main/scala/com/wavesplatform/network/DiscardingHandler.scala
  node/src/main/scala/com/wavesplatform/network/message/Message.scala
  node/src/main/scala/com/wavesplatform/network/messages.scala
  node/src/main/scala/com/wavesplatform/network/package.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/serialization/BytesSerializable.scala
  node/src/main/scala/com/wavesplatform/serialization/JsonSerializable.scala
  node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
  node/src/main/scala/com/wavesplatform/transaction/CreateAliasTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/DataTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/GenesisTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/LegacyPBSwitch.scala
  node/src/main/scala/com/wavesplatform/transaction/Transaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/BurnTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/IssueTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/ReissueTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/SetAssetScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/SponsorFeeTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/ExchangeTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/lease/LeaseCancelTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/lease/LeaseTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/package.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/BurnTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/CreateAliasTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/DataTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/ExchangeTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/InvokeScriptTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/IssueTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/LeaseCancelTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/LeaseTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/MassTransferTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/PBTransactionSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/PaymentTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/ReissueTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/SetAssetScriptTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/SetScriptTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/SponsorFeeTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/TransferTxSerializer.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/InvokeScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/SetScriptTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/script/ScriptRunner.scala
  node/src/main/scala/com/wavesplatform/transaction/transfer/MassTransferTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/transfer/TransferTransaction.scala
  node/src/test/scala/com/wavesplatform/database/LevelDBWriterSpec.scala
  node/src/test/scala/com/wavesplatform/transaction/InvokeScriptTransactionSpecification.scala
Labels: enhancement, feature
