Repository wavesplatform/Waves, pull requests merged in 2019-08, with the labels that each got.

#2476 NODE-1856: OrdersV3 support in gRPC
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBOrders.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/Order.scala
Labels: bug

#2475 NODE-1859: gRPC endpoint for alias resolution
  common/shared/src/main/scala/com/wavesplatform/common/utils/package.scala
  grpc-server/src/main/protobuf/accounts_api.proto
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AccountsApiGrpcImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AssetsApiGrpcImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/BlocksApiGrpcImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/GRPCErrors.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/TransactionsApiGrpcImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/package.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/ValidationError.scala
  node/src/main/scala/com/wavesplatform/api/common/CommonBlocksApi.scala
  node/src/main/scala/com/wavesplatform/api/http/ApiError.scala
  node/src/main/scala/com/wavesplatform/api/http/ApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/BlocksApiRoute.scala
  node/src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/UtilsRouteSpec.scala
Labels: enhancement

#2486 NODE-1838: Hide /blocks/child API route
  grpc-server/src/main/protobuf/blocks_api.proto
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/BlocksApiGrpcImpl.scala
  node/src/main/scala/com/wavesplatform/api/http/BlocksApiRoute.scala
Labels: refactoring

#2488 NODE-1806: Test for transferById optimization
  node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
  node/src/test/scala/com/wavesplatform/database/LevelDBWriterSpec.scala
Labels: refactoring

#2491 SC-420 Absolute paths in definitions of settings and tasks
  build.sbt
  project/Tasks.scala
Labels: dex

#2429 NODE-1828: Closeable iterator fixes
  benchmark/src/main/scala/com/wavesplatform/state/ExtractInfo.scala
  benchmark/src/test/scala/com/wavesplatform/state/LevelDBWriterBenchmark.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AccountsApiGrpcImpl.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/NFTBalanceSuite.scala
  node/src/main/scala/com/wavesplatform/api/common/CommonAccountApi.scala
  node/src/main/scala/com/wavesplatform/api/common/CommonTransactionsApi.scala
  node/src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/leasing/LeaseApiRoute.scala
  node/src/main/scala/com/wavesplatform/database/Caches.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBDistributions.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBWriterAddressTransactions.scala
  node/src/main/scala/com/wavesplatform/database/ReadOnlyDB.scala
  node/src/main/scala/com/wavesplatform/database/package.scala
  node/src/main/scala/com/wavesplatform/http/DebugApiRoute.scala
  node/src/main/scala/com/wavesplatform/settings/BlockchainSettings.scala
  node/src/main/scala/com/wavesplatform/state/Blockchain.scala
  node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
  node/src/main/scala/com/wavesplatform/state/diffs/AssetTransactionsDiff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/BalanceDiffValidation.scala
  node/src/main/scala/com/wavesplatform/state/extensions/AddressTransactions.scala
  node/src/main/scala/com/wavesplatform/state/extensions/BlockchainExtensions.scala
  node/src/main/scala/com/wavesplatform/state/extensions/Distributions.scala
  node/src/main/scala/com/wavesplatform/state/extensions/composite/CompositeAddressTransactions.scala
  node/src/main/scala/com/wavesplatform/state/extensions/composite/CompositeDistributions.scala
  node/src/main/scala/com/wavesplatform/state/package.scala
  node/src/main/scala/com/wavesplatform/state/patch/CancelLeaseOverflow.scala
  node/src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/IssueTransaction.scala
  node/src/main/scala/com/wavesplatform/utils/CloseableIterator.scala
  node/src/main/scala/com/wavesplatform/utils/EmptyBlockchain.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/database/LevelDBWriterSpec.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterBurnTest.scala
  node/src/test/scala/com/wavesplatform/history/Domain.scala
  node/src/test/scala/com/wavesplatform/http/DebugApiRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/settings/BlockchainSettingsSpecification.scala
  node/src/test/scala/com/wavesplatform/state/BlockchainUpdaterImplSpec.scala
  node/src/test/scala/com/wavesplatform/state/RollbackSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SetScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SponsorshipDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala
  node/src/test/scala/com/wavesplatform/state/utils/package.scala
  node/src/test/scala/com/wavesplatform/transaction/ReissueTransactionV2Specification.scala
  node/src/test/scala/com/wavesplatform/transaction/SponsorFeeTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
Labels: refactoring

#2503 NODE-1816: Silent old transaction drop
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/network/UtxPoolSynchronizer.scala
Labels: enhancement

#2517 NODE-1871: Stop node on DBException in block appender
  node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
  node/src/main/scala/com/wavesplatform/state/appender/package.scala
  node/src/main/scala/com/wavesplatform/utils/ApplicationStopReason.scala
  node/src/package/systemd.service
Labels: enhancement

#2514 PB and dependencies minor fixes
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBRecipients.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  project/Dependencies.scala
Labels: bug, refactoring

#2487 NODE-1858: Explorer args fix
  node/src/main/scala/com/wavesplatform/Explorer.scala
Labels: enhancement

#2524 NODE-1874: Minimal transaction fees change
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/BlockchainApiGrpcImpl.scala
  node-it/src/test/scala/com/wavesplatform/it/Node.scala
  node-it/src/test/scala/com/wavesplatform/it/WaitForHeight2.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/NFTBalanceSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/network/NetworkUniqueConnectionsTestSuite.scala
  node/src/main/scala/com/wavesplatform/account/Alias.scala
  node/src/main/scala/com/wavesplatform/features/BlockchainFeature.scala
  node/src/main/scala/com/wavesplatform/features/api/ActivationApiRoute.scala
  node/src/main/scala/com/wavesplatform/mining/Miner.scala
  node/src/main/scala/com/wavesplatform/network/HandshakeHandler.scala
  node/src/main/scala/com/wavesplatform/network/NetworkServer.scala
  node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
  node/src/main/scala/com/wavesplatform/state/diffs/FeeValidation.scala
  node/src/main/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiff.scala
  node/src/test/scala/com/wavesplatform/database/LevelDBWriterSpec.scala
  node/src/test/scala/com/wavesplatform/db/WithState.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterBadReferencesTest.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterBlockOnlyTest.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterGeneratorFeeNextBlockOrMicroBlockTest.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterGeneratorFeeSameBlockTest.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterInMemoryDiffTest.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterMicroblockBadSignaturesTest.scala
  node/src/test/scala/com/wavesplatform/history/BlockchainUpdaterMicroblockSunnyDayTest.scala
  node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/lagonaki/mocks/TestBlock.scala
  node/src/test/scala/com/wavesplatform/settings/TestFunctionalitySettings.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SponsorshipDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala
  node/src/test/scala/com/wavesplatform/transaction/TransactionFeesSpec.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
Labels: breaking, enhancement

#2426 NODE-1825: External proto schemes
  build.sbt
  grpc-server/build.sbt
  grpc-server/src/main/protobuf/accounts_api.proto
  grpc-server/src/main/protobuf/assets_api.proto
  grpc-server/src/main/protobuf/blockchain_api.proto
  grpc-server/src/main/protobuf/blocks_api.proto
  grpc-server/src/main/protobuf/transactions_api.proto
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AccountsApiGrpcImpl.scala
  node/build.sbt
  node/src/main/protobuf/block.proto
  node/src/main/protobuf/recipient.proto
  node/src/main/protobuf/script.proto
  node/src/main/protobuf/transaction.proto
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBAmounts.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBOrders.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/transaction.scala
  node/src/main/scala/com/wavesplatform/protobuf/utils/PBInternalImplicits.scala
  node/src/main/scala/com/wavesplatform/transaction/Asset.scala
  project/Dependencies.scala
Labels: refactoring
