Repository wavesplatform/Waves, pull requests merged in 2020-04, with the labels that each got.

#3012 NODE-1996: UTX event stream
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/Importer.scala
  node/src/main/scala/com/wavesplatform/events/UtxEvent.scala
  node/src/main/scala/com/wavesplatform/extensions/Context.scala
  node/src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
Labels: feature

#3025 NODE-2103: Fix block serializer
  node/src/main/scala/com/wavesplatform/block/serialization/BlockSerializer.scala
  node/src/main/scala/com/wavesplatform/block/validation/Validators.scala
  node/src/main/scala/com/wavesplatform/protobuf/block/PBBlocks.scala
  node/src/test/scala/com/wavesplatform/mining/BlockV5Test.scala
Labels: bug

#3039 NODE-2091: Account balance error message on API
  node-it/src/test/scala/com/wavesplatform/it/asset/IssueReissueBurnAssetSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/ApiError.scala
Labels: enhancement

#3037 NODE-2094: ExchangeTransaction validation error messages
  node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/ExchangeTransactionSuite.scala
  node/src/test/scala/com/wavesplatform/transaction/ExchangeTransactionSpecification.scala
Labels: tests

#3036 NODE-2075: Asset distribution json format test
  node/src/test/scala/com/wavesplatform/TestValues.scala
  node/src/test/scala/com/wavesplatform/api/http/AssetsApiRouteSpec.scala
  node/src/test/scala/com/wavesplatform/state/PortfolioTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
Labels: tests

#3038 NODE-2100: Fix pre-activated feature handling
  node-it/src/test/scala/com/wavesplatform/it/sync/activation/ActivationStatusRequest.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/activation/FeatureActivationTestSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/activation/PreActivatedFeaturesTestSuite.scala
  node/src/main/scala/com/wavesplatform/features/api/ActivationApiRoute.scala
  node/src/main/scala/com/wavesplatform/mining/Miner.scala
  node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
  node/src/test/scala/com/wavesplatform/mining/MiningFailuresSuite.scala
Labels: bug

#3051 NODE-2115: Transfers with different attachment types test
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/TransferTransactionSuite.scala
Labels: tests

#3042 NODE-2054: Add ChainID to InvokeScriptResult
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/TransactionsApiGrpcImpl.scala
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncGrpcApi.scala
  node-it/src/test/scala/com/wavesplatform/it/api/SyncGrpcApi.scala
  node-it/src/test/scala/com/wavesplatform/it/asset/GrpcIssueReissueBurnAssetSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/FailedTransactionGrpcSuite.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/state/InvokeScriptResult.scala
  project/Dependencies.scala
Labels: enhancement

#3055 NODE-2117: Add protobuf transactions support in the generator
  node-generator/src/main/resources/application.conf
  node-generator/src/main/scala/com/wavesplatform/generator/NarrowTransactionGenerator.scala
Labels: feature

#3049 NODE-2112: Single blockchain feature for the new functionality
  node-it/src/test/resources/template.conf
  node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/activation/AcceptFailedScriptActivationSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/activation/VRFProtobufActivationSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/EstimatorTestSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/InvokeCalcIssueSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/RideV4ActivationSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
  node/src/main/scala/com/wavesplatform/features/BlockchainFeature.scala
  node/src/main/scala/com/wavesplatform/features/EstimatorProvider.scala
  node/src/main/scala/com/wavesplatform/features/FunctionCallPolicyProvider.scala
  node/src/main/scala/com/wavesplatform/features/InvokeScriptSelfPaymentPolicyProvider.scala
  node/src/main/scala/com/wavesplatform/features/MultiPaymentPolicyProvider.scala
  node/src/main/scala/com/wavesplatform/features/OverdraftValidationProvider.scala
  node/src/main/scala/com/wavesplatform/features/ScriptTransferValidationProvider.scala
  node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
  node/src/main/scala/com/wavesplatform/state/diffs/DiffsCommon.scala
  node/src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/FeeValidation.scala
  node/src/main/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/TransactionDiffer.scala
  node/src/test/scala/com/wavesplatform/db/WithState.scala
  node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/DiffProduceError.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/LeaseTransactionsDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ReissueTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SponsorshipDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/CallableV4DiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/ListParamInvokeTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/MultiPaymentInvokeDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/OverdraftTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/package.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/TransactionBindingsTest.scala
Labels: enhancement

#3053 NODE-2110: Change PoS min block time to 30s
  node-it/src/test/scala/com/wavesplatform/it/sync/PoSSuite.scala
  node/src/main/scala/com/wavesplatform/consensus/PoSCalculator.scala
  node/src/main/scala/com/wavesplatform/consensus/PoSSelector.scala
  node/src/test/scala/com/wavesplatform/consensus/FPPoSSelectorTest.scala
  node/src/test/scala/com/wavesplatform/consensus/FairPoSCalculatorTest.scala
Labels: enhancement

#3061 NODE-2122: Fix UpdateAssetInfoTransaction broadcast
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/UpdateAssetInfoTransactionSuite.scala
  node/src/main/scala/com/wavesplatform/network/messages.scala
  node/src/main/scala/com/wavesplatform/protobuf/block/PBBlocks.scala
  node/src/main/scala/com/wavesplatform/transaction/ProtobufOnly.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/UpdateAssetInfoTransaction.scala
  node/src/test/scala/com/wavesplatform/TestValues.scala
  node/src/test/scala/com/wavesplatform/mining/BlockV5Test.scala
  node/src/test/scala/com/wavesplatform/network/LegacyFrameCodecSpec.scala
Labels: bug

#3079 NODE-2130: Fix BlockV5 import
  node/src/main/scala/com/wavesplatform/Importer.scala
Labels: bug

#2929 NODE-1919: Block apply span metrics
  node/src/main/resources/application.conf
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/Exporter.scala
  node/src/main/scala/com/wavesplatform/Importer.scala
  node/src/main/scala/com/wavesplatform/metrics/BlockStats.scala
  node/src/main/scala/com/wavesplatform/metrics/InfluxDBSpanReporter.scala
  node/src/main/scala/com/wavesplatform/metrics/Instrumented.scala
  node/src/main/scala/com/wavesplatform/metrics/LevelDBStats.scala
  node/src/main/scala/com/wavesplatform/metrics/Metrics.scala
  node/src/main/scala/com/wavesplatform/metrics/TxProcessingStats.scala
  node/src/main/scala/com/wavesplatform/metrics/package.scala
  node/src/main/scala/com/wavesplatform/mining/Miner.scala
  node/src/main/scala/com/wavesplatform/mining/microblocks/MicroBlockMinerImpl.scala
  node/src/main/scala/com/wavesplatform/network/TrafficWatcher.scala
  node/src/main/scala/com/wavesplatform/network/package.scala
  node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
  node/src/main/scala/com/wavesplatform/state/appender/BlockAppender.scala
  node/src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala
  project/Dependencies.scala
Labels: enhancement
