Repository wavesplatform/Waves, pull requests merged in 2020-05, with the labels that each got.

#3076 SC-573 Asset name and description test
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/RideIssueTransactionSuite.scala
Labels: wip

#3093 NODE-2137: Rollback InvokeScriptTransaction actions
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/asset/IssueReissueBurnAssetSuite.scala
  node/src/main/scala/com/wavesplatform/database/KeyTags.scala
  node/src/main/scala/com/wavesplatform/database/Keys.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
  node/src/main/scala/com/wavesplatform/database/package.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/state/RollbackSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
Labels: bug

#3085 NODE-1838: Fix blocks api (gRPC)
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/BlocksApiGrpcImpl.scala
  node-it/src/test/scala/com/wavesplatform/it/api/SyncGrpcApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/BlockV5GrpcSuite.scala
  project/Dependencies.scala
Labels: enhancement

#3106 NODE-2123: Multiple assets details (Swagger)
  node/src/main/resources/swagger-ui/swagger.json
Labels: enhancement

#3112 NODE-2121: Additional integration test
  node-it/src/test/scala/com/wavesplatform/it/asset/IssueReissueBurnAssetSuite.scala
Labels: tests

#3104 NODE-2071: Remove obsolete methods (REST API)
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/BlockV5TestSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/activation/VRFProtobufActivationSuite.scala
  node/src/main/resources/swagger-ui/swagger.json
  node/src/main/scala/com/wavesplatform/consensus/nxt/api/http/NxtConsensusApiRoute.scala
  node/src/main/scala/com/wavesplatform/http/DebugApiRoute.scala
  node/src/test/scala/com/wavesplatform/http/ConsensusRouteSpec.scala
Labels: enhancement

#3109 NODE-2126: Improve Swagger descriptions
  node/src/main/resources/swagger-ui/swagger.json
Labels: enhancement

#3105 NODE-1914: Count OrderV3 smart asset fee in complexity
  node/src/main/scala/com/wavesplatform/block/Block.scala
  node/src/main/scala/com/wavesplatform/block/package.scala
  node/src/main/scala/com/wavesplatform/block/validation/Validators.scala
  node/src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/ExchangeTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/Verifier.scala
  node/src/test/scala/com/wavesplatform/TestValues.scala
  node/src/test/scala/com/wavesplatform/history/Domain.scala
  node/src/test/scala/com/wavesplatform/history/package.scala
  node/src/test/scala/com/wavesplatform/state/diffs/BlockDifferTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/transaction/TxHelpers.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
Labels: bug

#3091 NODE-2128: Freeze patches
  blockchain-updates/src/main/scala/com/wavesplatform/events/protobuf/PBEvents.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AssetsApiGrpcImpl.scala
  node/src/main/resources/patches/CancelAllLeases-T.json
  node/src/main/resources/patches/CancelAllLeases-W.json
  node/src/main/resources/patches/CancelInvalidLeaseIn-W.json
  node/src/main/resources/patches/CancelLeaseOverflow-W.json
  node/src/main/resources/patches/DisableHijackedAliases-W.json
  node/src/main/scala/com/wavesplatform/api/common/AddressTransactions.scala
  node/src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
  node/src/main/scala/com/wavesplatform/database/Caches.scala
  node/src/main/scala/com/wavesplatform/database/Keys.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
  node/src/main/scala/com/wavesplatform/database/package.scala
  node/src/main/scala/com/wavesplatform/database/patch/DisableHijackedAliases.scala
  node/src/main/scala/com/wavesplatform/events/events.scala
  node/src/main/scala/com/wavesplatform/settings/BlockchainSettings.scala
  node/src/main/scala/com/wavesplatform/state/Blockchain.scala
  node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
  node/src/main/scala/com/wavesplatform/state/Diff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/AssetTransactionsDiff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/BlockDiffer.scala
  node/src/main/scala/com/wavesplatform/state/diffs/DiffsCommon.scala
  node/src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/TransactionDiffer.scala
  node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeDiffsCommon.scala
  node/src/main/scala/com/wavesplatform/state/patch/CancelAllLeases.scala
  node/src/main/scala/com/wavesplatform/state/patch/CancelInvalidLeaseIn.scala
  node/src/main/scala/com/wavesplatform/state/patch/CancelLeaseOverflow.scala
  node/src/main/scala/com/wavesplatform/state/patch/DiffPatchFactory.scala
  node/src/main/scala/com/wavesplatform/state/patch/PatchLoader.scala
  node/src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/Verifier.scala
  node/src/main/scala/com/wavesplatform/utils/package.scala
  node/src/test/scala/com/wavesplatform/api/http/AssetsApiRouteSpec.scala
  node/src/test/scala/com/wavesplatform/events/BlockchainUpdateTriggersSpec.scala
  node/src/test/scala/com/wavesplatform/settings/BlockchainSettingsSpecification.scala
  node/src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/MultiPaymentInvokeDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/patch/CancelAllLeasesTest.scala
  node/src/test/scala/com/wavesplatform/state/patch/CancelLeaseOverflowTest.scala
  node/src/test/scala/com/wavesplatform/transaction/smart/VerifierSpecification.scala
  node/src/test/scala/com/wavesplatform/utils/EmptyBlockchain.scala
Labels: enhancement
