Repository wavesplatform/Waves, pull requests merged in 2020-10, with the labels that each got.

#3226 BlockchainUpdates API extension
  blockchain-updates/build.sbt
  blockchain-updates/src/main/resources/application.conf
  blockchain-updates/src/main/scala/com/wavesplatform/events/BlockchainUpdates.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/api/grpc/BlockchainUpdatesApiGrpcImpl.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/api/grpc/backpressure.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/events.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/kafka/package.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/protobuf/PBEvents.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/repo/LiquidState.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/repo/Lockable.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/repo/UpdatesRepo.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/repo/UpdatesRepoImpl.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/settings/BlockchainUpdatesSettings.scala
  blockchain-updates/src/test/scala/com/wavesplatform/events/BlockchainUpdateTriggersSpec.scala
  blockchain-updates/src/test/scala/com/wavesplatform/events/EventsHelpers.scala
  blockchain-updates/src/test/scala/com/wavesplatform/events/GenesisBlockUpdateSpec.scala
  blockchain-updates/src/test/scala/com/wavesplatform/events/WithBlockchain.scala
  build.sbt
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/Importer.scala
  node/src/main/scala/com/wavesplatform/events/BlockchainUpdateTriggers.scala
  node/src/main/scala/com/wavesplatform/events/BlockchainUpdateTriggersImpl.scala
  node/src/main/scala/com/wavesplatform/events/events.scala
  node/src/main/scala/com/wavesplatform/extensions/Context.scala
  node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
  node/src/main/scala/com/wavesplatform/state/NgState.scala
  node/src/test/scala/com/wavesplatform/events/BlockchainUpdateTriggersSpec.scala
  node/src/test/scala/com/wavesplatform/events/EventsHelpers.scala
  node/src/test/scala/com/wavesplatform/events/GenesisBlockUpdateSpec.scala
  node/src/test/scala/com/wavesplatform/events/WithBlockchain.scala
  node/src/test/scala/com/wavesplatform/state/BlockchainUpdaterImplSpec.scala
  project/Dependencies.scala
Labels: enhancement

#3282 NODE-2246: Fix blockchain-updates work with importer
  blockchain-updates/src/main/scala/com/wavesplatform/events/repo/UpdatesRepoImpl.scala
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/Importer.scala
  node/src/main/scala/com/wavesplatform/events/BlockchainUpdateTriggers.scala
Labels: bug

#3286 NODE-2211: Continue import from auto-calculated offset
  node/src/main/scala/com/wavesplatform/Exporter.scala
  node/src/main/scala/com/wavesplatform/Importer.scala
Labels: enhancement

#3291 NODE-2255: Fix docker image
  docker/Dockerfile
  docker/README.md
  docker/entrypoint.sh
Labels: bug

#3283 NODE-2247: Move BlockchainUpdates extension to grpc-server module
  blockchain-updates/build.sbt
  blockchain-updates/src/main/resources/application.conf
  blockchain-updates/src/main/scala/com/wavesplatform/events/api/grpc/backpressure.scala
  build.sbt
  grpc-server/build.sbt
  grpc-server/src/main/resources/application.conf
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/package.scala
  grpc-server/src/main/scala/com/wavesplatform/events/BlockchainUpdates.scala
  grpc-server/src/main/scala/com/wavesplatform/events/api/grpc/BlockchainUpdatesApiGrpcImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/events/events.scala
  grpc-server/src/main/scala/com/wavesplatform/events/protobuf/PBEvents.scala
  grpc-server/src/main/scala/com/wavesplatform/events/repo/LiquidState.scala
  grpc-server/src/main/scala/com/wavesplatform/events/repo/Lockable.scala
  grpc-server/src/main/scala/com/wavesplatform/events/repo/UpdatesRepo.scala
  grpc-server/src/main/scala/com/wavesplatform/events/repo/UpdatesRepoImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/events/settings/BlockchainUpdatesSettings.scala
  grpc-server/src/test/scala/com/wavesplatform/events/BlockchainUpdateTriggersSpec.scala
  grpc-server/src/test/scala/com/wavesplatform/events/EventsHelpers.scala
  grpc-server/src/test/scala/com/wavesplatform/events/GenesisBlockUpdateSpec.scala
  grpc-server/src/test/scala/com/wavesplatform/events/WithBlockchain.scala
  project/WavesExtensionDockerPlugin.scala
Labels: refactoring

#3289 NODE-2249: BlockchainUpdates fixes
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/package.scala
  grpc-server/src/main/scala/com/wavesplatform/events/BlockchainUpdates.scala
  grpc-server/src/main/scala/com/wavesplatform/events/api/grpc/BlockchainUpdatesApiGrpcImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/events/events.scala
  grpc-server/src/main/scala/com/wavesplatform/events/protobuf/PBEvents.scala
  grpc-server/src/main/scala/com/wavesplatform/events/repo/Lockable.scala
  grpc-server/src/main/scala/com/wavesplatform/events/repo/UpdatesRepo.scala
  grpc-server/src/main/scala/com/wavesplatform/events/repo/UpdatesRepoImpl.scala
  grpc-server/src/test/scala/com/wavesplatform/events/BlockchainUpdatesSpec.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
  node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
  node/src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
  node/src/main/scala/com/wavesplatform/utils/OptimisticLockable.scala
  node/src/test/scala/com/wavesplatform/db/WithState.scala
Labels: bug

#3295 NODE-2249: Fix blockchain-updates zero toHeight and error messages
  build.sbt
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/package.scala
  grpc-server/src/main/scala/com/wavesplatform/events/api/grpc/BlockchainUpdatesApiGrpcImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/events/repo/UpdatesRepoImpl.scala
  grpc-server/src/test/scala/com/wavesplatform/events/BlockchainUpdatesSpec.scala
Labels: bug
