Repository wavesplatform/Waves, pull requests merged in 2020-02, with the labels that each got.

#2904 NODE-2042: UTX priority pool
  node/src/main/resources/application.conf
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/Importer.scala
  node/src/main/scala/com/wavesplatform/metrics/BlockStats.scala
  node/src/main/scala/com/wavesplatform/mining/MiningConstraints.scala
  node/src/main/scala/com/wavesplatform/network/package.scala
  node/src/main/scala/com/wavesplatform/settings/MinerSettings.scala
  node/src/main/scala/com/wavesplatform/settings/UtxSettings.scala
  node/src/main/scala/com/wavesplatform/state/appender/package.scala
  node/src/main/scala/com/wavesplatform/utx/UtxPool.scala
  node/src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala
  node/src/test/scala/com/wavesplatform/mining/BlockWithMaxBaseTargetTest.scala
  node/src/test/scala/com/wavesplatform/mining/MiningFailuresSuite.scala
  node/src/test/scala/com/wavesplatform/mining/MiningWithRewardSuite.scala
  node/src/test/scala/com/wavesplatform/settings/MinerSettingsSpecification.scala
  node/src/test/scala/com/wavesplatform/settings/UtxSettingsSpecification.scala
  node/src/test/scala/com/wavesplatform/state/BlockchainUpdaterImplSpec.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
Labels: enhancement

#2920 NODE-2047: InvokeScript V2 reject empty data keys
  node/src/main/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiff.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
Labels: enhancement

#2926 NODE-2052: Fix SetAssetScriptV2
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/PBImplicitConversions.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/TransactionsApiGrpcImpl.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/CreateAliasTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/DataTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/IssueTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/LeasingTransactionsGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/MassTransferTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/UpdateAssetInfoTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/SetAssetScriptTransactionSuite.scala
  node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/SetAssetScriptTxValidator.scala
  node/src/test/scala/com/wavesplatform/state/diffs/CommonValidationTest.scala
  node/src/test/scala/com/wavesplatform/transaction/SetAssetScriptTransactionSpecification.scala
Labels: bug

#2930 NODE-2056: Fix account scripts (gRPC)
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AccountsApiGrpcImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AssetsApiGrpcImpl.scala
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncGrpcApi.scala
  node-it/src/test/scala/com/wavesplatform/it/api/SyncGrpcApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/InvokeScriptTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/SetAssetScriptGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/SetScriptTransactionGrpcSuite.scala
  node/src/main/scala/com/wavesplatform/api/common/CommonAccountApi.scala
  node/src/main/scala/com/wavesplatform/api/http/AddressApiRoute.scala
Labels: breaking, enhancement

#2940 NODE-2066-refactoring-InvokeScriptTransactionDiff
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/InvokeMultiplePaymentsSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/RideV4ActivationSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/ApiError.scala
  node/src/main/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiff.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
Labels: hold
