Repository wavesplatform/Waves, pull requests merged in 2020-03, with the labels that each got.

#2966 NODE-2077: Remove script object (protobuf)
  blockchain-updates/build.sbt
  blockchain-updates/src/main/protobuf/events.proto
  blockchain-updates/src/main/scala/com/wavesplatform/events/kafka/package.scala
  blockchain-updates/src/main/scala/com/wavesplatform/events/protobuf/PBEvents.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AccountsApiGrpcImpl.scala
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AssetsApiGrpcImpl.scala
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncGrpcApi.scala
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/api/SyncGrpcApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/InvokeScriptTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/SetAssetScriptGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/SetScriptTransactionGrpcSuite.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala
  node/src/main/scala/com/wavesplatform/state/InvokeScriptResult.scala
Labels: enhancement

#2968 NODE-2074: New LevelDB
  lang/shared/src/main/scala/com/wavesplatform/common/state/ByteStr.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBFactory.scala
  node/src/main/scala/com/wavesplatform/database/jna/LevelDBJNADB.scala
  node/src/main/scala/com/wavesplatform/database/jna/LevelDBJNADBFactory.scala
  node/src/main/scala/com/wavesplatform/transaction/Transaction.scala
  project/Dependencies.scala
Labels: enhancement

#2915 [SC-546] Tests for DeleteEntry function
  node-it/src/test/scala/com/wavesplatform/it/BaseSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/account/storage/RemoveEntrySuite.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/script/trace/TraceStep.scala
Labels: wip

#3015 NODE-2099: Fix address data list (REST, gRPC)
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/DataTransactionSuite.scala
  node/src/main/scala/com/wavesplatform/api/common/CommonAccountsApi.scala
  node/src/test/scala/com/wavesplatform/http/CommonAccountsApiSpec.scala
  node/src/test/scala/com/wavesplatform/settings/TestFunctionalitySettings.scala
Labels: bug

#3014 NODE-2070: Fix PB microblocks network format
  blockchain-updates/src/main/scala/com/wavesplatform/events/protobuf/PBEvents.scala
  node/src/main/scala/com/wavesplatform/events/BlockchainUpdateTriggers.scala
  node/src/main/scala/com/wavesplatform/events/BlockchainUpdateTriggersImpl.scala
  node/src/main/scala/com/wavesplatform/network/BasicMessagesRepo.scala
  node/src/main/scala/com/wavesplatform/protobuf/block/PBMicroBlocks.scala
  node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
  node/src/main/scala/com/wavesplatform/state/NgState.scala
  node/src/test/scala/com/wavesplatform/events/EventsHelpers.scala
  node/src/test/scala/com/wavesplatform/state/BlockchainUpdaterImplSpec.scala
Labels: breaking, enhancement

#3013 NODE-2098: Fix blocks by id (REST API)
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/AmountAsStringSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/BlockV5TestSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/activation/VRFProtobufActivationSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/UpdateAssetInfoTransactionSuite.scala
  node/src/main/resources/swagger-ui/swagger.json
  node/src/main/scala/com/wavesplatform/api/http/BlocksApiRoute.scala
  node/src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/BlocksRouteSpec.scala
Labels: enhancement
