Repository wavesplatform/Waves, pull requests merged in 2021-09, with the labels that each got.

#3537 NODE-2350: Typed invocation args in InvokeScriptResult
  build.sbt
  grpc-server/src/main/scala/com/wavesplatform/events/events.scala
  grpc-server/src/test/scala/com/wavesplatform/events/BlockchainUpdatesSpec.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/InvokeScriptTransactionGrpcSuite.scala
  node/src/main/scala/com/wavesplatform/state/InvokeScriptResult.scala
Labels: enhancement, breaking

#3544 NODE-2347: Set default minimum-peers to 1 (REST API)
  node/src/main/resources/application.conf
Labels: enhancement

#3543 NODE-2345: Configurable heavy request processor pool size
  node-it/src/test/scala/com/wavesplatform/it/BaseTargetChecker.scala
  node/src/main/resources/application.conf
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/Importer.scala
  node/src/main/scala/com/wavesplatform/api/http/CompositeHttpService.scala
  node/src/main/scala/com/wavesplatform/settings/RestAPISettings.scala
  node/src/main/scala/com/wavesplatform/settings/SynchronizationSettings.scala
  node/src/test/scala/com/wavesplatform/consensus/FPPoSSelectorTest.scala
  node/src/test/scala/com/wavesplatform/mining/BlockV5Test.scala
  node/src/test/scala/com/wavesplatform/mining/BlockWithMaxBaseTargetTest.scala
  node/src/test/scala/com/wavesplatform/mining/MiningFailuresSuite.scala
  node/src/test/scala/com/wavesplatform/mining/MiningWithRewardSuite.scala
  node/src/test/scala/com/wavesplatform/settings/RestAPISettingsSpecification.scala
  node/src/test/scala/com/wavesplatform/settings/SynchronizationSettingsSpecification.scala
Labels: feature

#3539 NODE-2312: Require wallet seed match
  node/src/main/scala/com/wavesplatform/wallet/Wallet.scala
  node/src/test/scala/com/wavesplatform/lagonaki/unit/WalletSpecification.scala
Labels: enhancement

#3545 NODE-2351: Multi-asset balance route (REST API)
  node/src/main/resources/swagger-ui/openapi.yaml
  node/src/main/scala/com/wavesplatform/api/http/CustomDirectives.scala
  node/src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
  node/src/test/scala/com/wavesplatform/http/AssetsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/RouteSpec.scala
Labels: feature
