Repository wavesplatform/Waves, pull requests merged in 2021-12, with the labels that each got.

#3595 NODE-2364: Rename feature 17 to "Ride V6, MetaMask support, Invoke Expression"
  node/src/main/scala/com/wavesplatform/features/BlockchainFeature.scala
  node/src/test/scala/com/wavesplatform/http/DebugApiRouteSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/freecall/InvokeExpressionTest.scala
  node/src/test/scala/com/wavesplatform/transaction/smart/EthereumTransactionSpec.scala
Labels: enhancement

#3591 NODE-2363: Fix Ethereum transaction ID calculation
  benchmark/src/test/scala/com/wavesplatform/lang/v1/AddressFromPublicKeyBenchmark.scala
  grpc-server/src/test/scala/com/wavesplatform/api/grpc/test/GRPCBroadcastSpec.scala
  grpc-server/src/test/scala/com/wavesplatform/events/BlockchainUpdatesSpec.scala
  node/src/main/scala/com/wavesplatform/transaction/EthereumTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/utils/EthTxGenerator.scala
  node/src/test/scala/com/wavesplatform/http/TransactionBroadcastSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/eth/EthereumInvokeTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/eth/EthereumTransferSmartTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala
  node/src/test/scala/com/wavesplatform/transaction/assets/exchange/EthOrderSpec.scala
  node/src/test/scala/com/wavesplatform/transaction/smart/EthereumTransactionSpec.scala
  node/src/test/scala/com/wavesplatform/utils/EthHelpers.scala
  project/Dependencies.scala
Labels: bug

#3602 NODE-2407: Allow comments inside RIDE func declaration
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/compiler/ContractCompilerTest.scala
Labels: bug

#3569 NODE Ethereum tests and fixes
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Functions.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/WavesEnvironment.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/eth/EthereumInvokeTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/eth/EthereumTransferSmartTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/package.scala
Labels: wip

#3594 NODE-2365: Strictly require a public key hash to be 20 bytes long
  node/src/main/scala/com/wavesplatform/account/Recipient.scala
  node/src/test/scala/com/wavesplatform/transaction/smart/EthereumTransactionSpec.scala
  node/src/test/scala/com/wavesplatform/utils/EthHelpers.scala
Labels: enhancement

#3600 NODE-2283 Add weak public key checks for all signatures verifying
  node-it/src/test/scala/com/wavesplatform/it/BaseTargetChecker.scala
  node-it/src/test/scala/com/wavesplatform/it/Docker.scala
  node/src/main/scala/com/wavesplatform/GenesisBlockGenerator.scala
  node/src/main/scala/com/wavesplatform/api/http/AddressApiRoute.scala
  node/src/main/scala/com/wavesplatform/block/Block.scala
  node/src/main/scala/com/wavesplatform/block/MicroBlock.scala
  node/src/main/scala/com/wavesplatform/block/package.scala
  node/src/main/scala/com/wavesplatform/block/validation/Validators.scala
  node/src/main/scala/com/wavesplatform/consensus/PoSSelector.scala
  node/src/main/scala/com/wavesplatform/crypto/package.scala
  node/src/main/scala/com/wavesplatform/network/MicroBlockSynchronizer.scala
  node/src/main/scala/com/wavesplatform/network/messages.scala
  node/src/main/scala/com/wavesplatform/package.scala
  node/src/main/scala/com/wavesplatform/state/appender/MicroblockAppender.scala
  node/src/main/scala/com/wavesplatform/transaction/PaymentTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/Signed.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/Verifier.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/script/ScriptRunner.scala
  node/src/main/scala/com/wavesplatform/utils/UtilApp.scala
  node/src/test/scala/com/wavesplatform/crypto/SigningFunctionsSpecification.scala
  node/src/test/scala/com/wavesplatform/network/MicroBlockInvSpecSpec.scala
  node/src/test/scala/com/wavesplatform/state/TransactionsByAddressSpec.scala
  node/src/test/scala/com/wavesplatform/transaction/ChainIdSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/InvokeScriptTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/OrderSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/assets/exchange/OrderJsonSpecification.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
Labels: wip

#3598 NODE-2368 Process InvokeExpression and Ethereum transactions for get asset info
  lang/testkit/src/main/scala/com/wavesplatform/lang/v1/testing/TypedScriptGen.scala
  node/src/main/scala/com/wavesplatform/api/common/CommonAccountsApi.scala
  node/src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/http/AssetsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/LeaseRouteSpec.scala
  node/src/test/scala/com/wavesplatform/transaction/TxHelpers.scala
Labels: bug
