Repository wavesplatform/Waves, pull requests merged in 2021-04, with the labels that each got.

#3411 NODE-2303: Blocks height by timestamp route (REST API)
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/api/http/BlocksApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/package.scala
  node/src/test/scala/com/wavesplatform/http/BlocksApiRouteSpec.scala
Labels: feature

#3427 NODE-2290: Check remote score before applying extension
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/Importer.scala
  node/src/main/scala/com/wavesplatform/network/RxExtensionLoader.scala
  node/src/main/scala/com/wavesplatform/network/RxScoreObserver.scala
  node/src/main/scala/com/wavesplatform/network/package.scala
  node/src/main/scala/com/wavesplatform/package.scala
  node/src/main/scala/com/wavesplatform/state/appender/BlockAppender.scala
  node/src/main/scala/com/wavesplatform/state/appender/ExtensionAppender.scala
  node/src/main/scala/com/wavesplatform/state/appender/package.scala
  node/src/test/scala/com/wavesplatform/features/RideV5LimitsChangeTest.scala
  node/src/test/scala/com/wavesplatform/network/RxExtensionLoaderSpec.scala
  node/src/test/scala/com/wavesplatform/network/RxScoreObserverSpec.scala
  node/src/test/scala/com/wavesplatform/state/appender/ExtensionAppenderSpec.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPriorityPoolSpecification.scala
Labels: enhancement

#3417 NODE-2302: Lease info route (REST API)
  grpc-server/src/main/scala/com/wavesplatform/api/grpc/AccountsApiGrpcImpl.scala
  node-it/src/test/scala/com/wavesplatform/it/api/model.scala
  node/src/main/protobuf/waves/database.proto
  node/src/main/resources/swagger-ui/swagger.json
  node/src/main/scala/com/wavesplatform/Application.scala
  node/src/main/scala/com/wavesplatform/api/common/CommonAccountsApi.scala
  node/src/main/scala/com/wavesplatform/api/common/LeaseInfo.scala
  node/src/main/scala/com/wavesplatform/api/http/leasing/LeaseApiRoute.scala
  node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
  node/src/main/scala/com/wavesplatform/database/package.scala
  node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
  node/src/main/scala/com/wavesplatform/state/diffs/DiffsCommon.scala
  node/src/main/scala/com/wavesplatform/state/diffs/LeaseTransactionsDiff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeDiffsCommon.scala
  node/src/main/scala/com/wavesplatform/state/patch/CancelAllLeases.scala
  node/src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
  node/src/main/scala/com/wavesplatform/state/reader/LeaseDetails.scala
  node/src/test/scala/com/wavesplatform/api/common/CommonAccountApiSpec.scala
  node/src/test/scala/com/wavesplatform/api/http/CustomJsonMarshallerSpec.scala
  node/src/test/scala/com/wavesplatform/http/DebugApiRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/LeaseRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/RouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/state/RollbackSpec.scala
Labels: feature

#3436 NODE-2311: Save intermediate invokes in state changes for failed invoke script transactions
  lang/shared/src/main/scala/com/wavesplatform/lang/directives/values/StdLibVersion.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Functions.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/SelfPaymentDappToDappSuite.scala
  node/src/main/scala/com/wavesplatform/api/http/DebugApiRoute.scala
  node/src/main/scala/com/wavesplatform/api/http/UtilsApiRoute.scala
  node/src/main/scala/com/wavesplatform/state/Diff.scala
  node/src/main/scala/com/wavesplatform/state/InvokeScriptResult.scala
  node/src/main/scala/com/wavesplatform/state/diffs/TransactionDiffer.scala
  node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeDiffsCommon.scala
  node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptDiff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/transaction/TxValidationError.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/WavesEnvironment.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/script/trace/CoevalR.scala
  node/src/main/scala/com/wavesplatform/transaction/smart/script/trace/TraceStep.scala
  node/src/test/scala/com/wavesplatform/db/WithState.scala
  node/src/test/scala/com/wavesplatform/features/RideV5LimitsChangeTest.scala
  node/src/test/scala/com/wavesplatform/history/Domain.scala
  node/src/test/scala/com/wavesplatform/history/LeasingExpirySpec.scala
  node/src/test/scala/com/wavesplatform/http/DebugApiRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/UtilsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/transaction/smart/SubInvokeStateChangesSpec.scala
Labels: enhancement

#3422 NODE-2308: Change lease state changes json schema (REST API)
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/traits/domain/CallableAction.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/LeaseStatusTestSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/LeasingTransactionsSuite.scala
  node/src/main/scala/com/wavesplatform/api/common/CommonAccountsApi.scala
  node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
  node/src/main/scala/com/wavesplatform/state/InvokeScriptResult.scala
  node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeDiffsCommon.scala
  node/src/test/scala/com/wavesplatform/http/DebugApiRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/LeaseRouteSpec.scala
  node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
  project/Dependencies.scala
Labels: enhancement

#3449 SC-759 Add payments limit test
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokePaymentsLimitTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
Labels: tests

#3448 NODE-2319: Fix nested invokes lease state changes format (REST API)
  node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
  node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
Labels: bug, enhancement

#3452 SC-751 Correct lang-doc module compilation
  lang/doc/src/main/scala/com/wavesplatform/utils/DocExport.scala
  lang/doc/src/main/scala/com/wavesplatform/utils/doc/DocExport.scala
  lang/doc/src/main/scala/com/wavesplatform/utils/doc/DocExportV3.scala
  lang/doc/src/main/scala/com/wavesplatform/utils/doc/RideFullContext.scala
Labels: bug, internal

#3455 SC-764 Increase callable limit to 10000
  lang/js/src/main/scala/JsAPI.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/script/ContractScript.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/ContractLimits.scala
  node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptTransactionDiff.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ci/CallableV5LimitTest.scala
Labels: enhancement
