Repository wavesplatform/Waves, pull requests merged in 2022-01, with the labels that each got.

#3588 NODE-2362: New data entries limit calculation
  node-it/src/test/scala/com/wavesplatform/it/api/AsyncGrpcApi.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/DataTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/DataTransactionBodyBytesByteVectorSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/DataTransactionSuite.scala
  node/src/main/scala/com/wavesplatform/network/BasicMessagesRepo.scala
  node/src/main/scala/com/wavesplatform/state/DataEntry.scala
  node/src/main/scala/com/wavesplatform/state/diffs/DataTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeDiffsCommon.scala
  node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptDiff.scala
  node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/transaction/DataTransaction.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/TxConstraints.scala
  node/src/main/scala/com/wavesplatform/transaction/validation/impl/DataTxValidator.scala
  node/src/test/scala/com/wavesplatform/history/Domain.scala
  node/src/test/scala/com/wavesplatform/transaction/DataTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/TxHelpers.scala
  node/src/test/scala/com/wavesplatform/transaction/data/DataTransactionNewLimitsSpec.scala
Labels: enhancement

#3599 NODE-2369: Add the old price mode for OrderV4
  .scalafmt.conf
  benchmark/src/test/scala/com/wavesplatform/serialization/protobuf/SmartNoSmartBenchmark.scala
  grpc-server/src/test/scala/com/wavesplatform/api/grpc/test/GRPCBroadcastSpec.scala
  grpc-server/src/test/scala/com/wavesplatform/events/BlockchainUpdatesSpec.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/activation/AcceptFailedScriptActivationSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/ExchangeTransactionSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/FailedTransactionSuiteLike.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/utils/TransactionSerializeSuite.scala
  node/src/main/scala/com/wavesplatform/protobuf/transaction/PBOrders.scala
  node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
  node/src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/EthOrders.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/Order.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderJson.scala
  node/src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderPriceMode.scala
  node/src/main/scala/com/wavesplatform/transaction/serialization/impl/OrderSerializer.scala
  node/src/test/scala/com/wavesplatform/TransactionGen.scala
  node/src/test/scala/com/wavesplatform/http/TransactionBroadcastSpec.scala
  node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/transaction/ExchangeTransactionSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/OrderSpecification.scala
  node/src/test/scala/com/wavesplatform/transaction/TxHelpers.scala
  node/src/test/scala/com/wavesplatform/transaction/assets/exchange/EthOrderSpec.scala
  node/src/test/scala/com/wavesplatform/transaction/assets/exchange/OrderJsonSpecification.scala
  node/src/test/scala/com/wavesplatform/utils/EthHelpers.scala
Labels: feature

#3622 SC-803: Unignore FractionIntRoundsTest
  lang/tests/src/test/scala/com/wavesplatform/lang/evaluator/math/FractionIntRoundsTest.scala
Labels: tests, internal

#3621 NODE-2418: Hide transaction constructors from Ride V6 context
  lang/shared/src/main/scala/com/wavesplatform/lang/script/v1/ExprScript.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Bindings.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Functions.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Types.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/v1/estimator/ScriptEstimatorTestBase.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SetScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/freecall/InvokeExpressionTest.scala
  node/src/test/scala/com/wavesplatform/transaction/TxHelpers.scala
Labels: enhancement, smart-contracts

#3625 NODE-2370: Reject non-string types in makeString V6 (RIDE)
  lang/shared/src/main/scala/com/wavesplatform/lang/script/v1/ExprScript.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/evaluator/EvaluatorSpec.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/evaluator/MakeStringTest.scala
Labels: enhancement, smart-contracts

#3623 NODE-2410 Fix sync call in dapp verifier check
  lang/shared/src/main/scala/com/wavesplatform/lang/contract/DApp.scala
  node/src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/SetScriptTransactionDiffTest.scala
  node/src/test/scala/com/wavesplatform/state/diffs/smart/predef/DAppVerifierRestrictionsTest.scala
Labels: bug, smart-contracts

#3626 NODE-2414: Update Scala.js to 1.8.0
  build.sbt
  node/build.sbt
  project/build.properties
  project/plugins.sbt
  repl/js/src/main/scala/JsAPI.scala
  repl/js/src/main/scala/com/wavesplatform/lang/v1/repl/Global.scala
  repl/js/src/main/scala/com/wavesplatform/lang/v1/repl/JsCompat.scala
  repl/jvm/src/main/scala/com/wavesplatform/lang/v1/repl/JsCompat.scala
  repl/shared/src/main/scala/com/wavesplatform/lang/v1/repl/Repl.scala
  repl/shared/src/main/scala/com/wavesplatform/lang/v1/repl/node/http/NodeClient.scala
  repl/shared/src/main/scala/com/wavesplatform/lang/v1/repl/node/http/WebEnvironment.scala
Labels: internal, smart-contracts

#3624 NODE-2408 Version dependent type cast macro
  lang/jvm/src/main/scala/com/wavesplatform/lang/JavaAdapter.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/script/ContractScript.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/CTX.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerContext.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/ExpressionCompiler.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/TypeCast.scala
  lang/testkit/src/main/scala/com/wavesplatform/lang/v1/compiler/TestCompiler.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/compiler/ContractCompilerTest.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/compiler/DecompilerTest.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/compiler/ExpressionCompilerV1Test.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/compiler/MetaTest.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/compiler/names/NameDuplicationTest.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
  repl/shared/src/main/scala/com/wavesplatform/lang/v1/repl/Repl.scala
Labels: bug, smart-contracts

#3627 NODE-2370: Fix makeString in unfixed contexts
  lang/shared/src/main/scala/com/wavesplatform/lang/utils/package.scala
  lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/evaluator/BytesDropTakeTest.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/evaluator/EvaluatorSpec.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/evaluator/MakeStringTest.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/evaluator/string/StringFunctionsTest.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/v1/estimator/FunctionComplexityTest.scala
  node/src/main/scala/com/wavesplatform/Importer.scala
Labels: bug, smart-contracts

#3585 NODE-2360: Don't use a composite diff in the UTX cleanup
  node-it/src/test/scala/com/wavesplatform/it/sync/grpc/CreateAliasTransactionGrpcSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/AssetSupportedTransactionsSuite.scala
  node-it/src/test/scala/com/wavesplatform/it/sync/transactions/AliasTransactionSuite.scala
  node/src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala
  node/src/main/scala/com/wavesplatform/utx/UtxPriorityPool.scala
  node/src/test/scala/com/wavesplatform/history/Domain.scala
  node/src/test/scala/com/wavesplatform/utx/UtxFailedTxsSpec.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
  node/src/test/scala/com/wavesplatform/utx/UtxPriorityPoolSpecification.scala
Labels: enhancement, internal

#3619 NODE-2416: Support underscores and dashes for directive values
  lang/shared/src/main/scala/com/wavesplatform/lang/directives/DirectiveParser.scala
  lang/tests/src/test/scala/com/wavesplatform/lang/DirectiveParserTest.scala
Labels: enhancement, smart-contracts
